### PR TITLE
Fix HomeAssistant autodiscovery not working with HomeAssistant v0.69+

### LINKED ISSUE #42: HomeAssistant integration is broken with HomeAssistant v0.69
(I intend to fix this myself and submit a PR, consider this a bug report so others know that the integration is not expected to work right now)

HomeAssistant v0.69 changed the schema for defining sensor objects via MQTT (see home-assistant/home-assistant#14033) which means that the objects published by this script are no longer valid

### PR DESCRIPTION
**Pull request by insertjokehere**
Fixes #42

### CODE REVIEW

**Comment by zerog2k** [comment]
Thanks. Just ran across this myself and was going to try to submit a pr to fix... Glad someone beat me to it. Just +1'ing this here, as it solves the issue for me as well.

Would it also be possible to add the homeassistant-json type info to the config example?
https://github.com/ThomDietrich/miflora-mqtt-daemon/blob/master/config.ini.dist#L8

I didn't see anything in readme or sample config about how to configure the support, and had to dig into the code to find it.

**Comment by ThomDietrich** [comment]
Thanks @insertjokehere! Happy to see this integration working again. 🎉

**Comment by ThomDietrich** [comment]
@zerog2k satisfied? :) https://github.com/ThomDietrich/miflora-mqtt-daemon/pull/47

**Comment by zerog2k** [comment]
Thanks!

**Pull request merged**
