### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by martinlindjarv**
#128 
To latest miflora (0.7.1) and btlewrap (0.0.10).

### CODE REVIEW

**Comment by GuyKh** [comment]
Tested and can assure it works.

**Comment by StohanzlMart** [comment]
@ThomDietrich merge please?

**Comment by StohanzlMart** [comment]
Jesus, @ThomDietrich PLEASE merge :)

**Comment by ThomDietrich** [comment]
Thanks for the push. Really sorry I didn't react earlier. Pretty busy atm and not happy what that does to my open source engagement :(

**Comment by StohanzlMart** [comment]
Thank you for sharing your project!

**Pull request merged**
