### PR TITLE
Upgraded to homie 3.0 convention and one connection per device for homie

### PR DESCRIPTION
**Pull request by chrostek**
Solves #57

### CODE REVIEW

**Comment by NorbertHD** [comment]
@chrostek thank you for your contribution, but I get an exception log entry in openhab with your code and the sensor item shows offline

```
2020-05-20 17:25:24.370 [hingStatusInfoChangedEvent] - 'mqtt:homie300:mosquitto:crassulaovata' changed from INITIALIZING to OFFLINE (COMMUNICATION_ERROR): java.lang.Exception: Did not receive mandatory topic value: homie/crassulaovata/$name
```

**Comment by chrostek** [comment]
I think it is a bug in openHAB - i have this error with other homie implementations too (volkszaehler/mbmd).
openHAB needs to receive this topic after the device was added or after openhab started - please restart miflora-mqtt-daemon after adding the device and the error will disappear

**Comment by ThomDietrich** [comment]
@chrostek Thanks! Really sorry this one got lost in the past. I've merged it now but I have no environment to test atm. Please let me know when you get around testing it!

**Comment by chrostek** [comment]
@ThomDietrich thanks! i use/test this since May 2020 - it works without any issues with the latest openhab versions

**Comment by ThomDietrich** [comment]
Great!
As you might know from #111 I was planning to move to a different software structure. I am not sure when I'll have the time to do so but I'd be happy if I could refer back to you for improvements and testing?

Best!

**Comment by chrostek** [comment]
i am no developer, i did only a bit copy & paste ;-)
but i am happy to help you with testing

**Pull request merged**
