### PR TITLE
Docker images for arm32v6, arm32v7 and arm64v8

### PR DESCRIPTION
**Pull request by RaymondMouthaan**
Hello Thom,

I took the opportunity to create docker images for the architectures arm32v6 (RPI 1, 2, 3 and Zero), arm32v7 (RPI 1, 2, 3) and arm64v8 (pine64), so that users of RPI 1, 2, 3 and Zero can run miflora-mqtt-daemon within a docker container without building the image by there self. The readme is updated accordingly.

The build process is automated by Travis, which gets triggered by a github commit. When such commit is is done, then Travis checks if it is a release, if yes then the images are build and tested and pushed to Docker Hub, if not the images are build and tested but not pushed to Docker Hub.

I've tested the arm32v6 and arm32v7 images on a Raspberry PI 3, and both run as aspected. I have no Pine64 devices available, so the arm64v8 isn't tested, but I am quit confident that it will work.

The images can be found here [raymondmm/miflora-mqtt](https://hub.docker.com/r/raymondmm/miflora-mqtt/tags/).

Hope you appreciate the work.

Best regards,
Raymond

### CODE REVIEW

**Comment by RaymondMouthaan** [comment]
Hi Thom,

No special reason, it's only shorter for one who uses volume persist.

E.g. ' -v <mymiflora_config_path>:/config' 

Where mymiflora_config_path is the path on the docker host system and /config the config path inside the docker container.

Hope this explains it 😇

**Comment by RaymondMouthaan** [comment]
For anyone who is interested, the latest Docker images can be found here: [miflora2mqtt](https://hub.docker.com/repository/docker/raymondmm/miflora2mqtt/general)

**Comment by baurmatt** [comment]
Hey, any specific reason why this hasn't been merged? This looks definitely better as the basic Dockerfile which is currently in the repository.

**Comment by ThomDietrich** [comment]
I agree. I would love to bring this back in. Would you @baurmatt be able to create a new pull request to discuss? Thanks!

**Comment by baurmatt** [comment]
@ThomDietrich Sure, but lets wait if @RaymondMouthaan want's to do it himself as he probably just would have to reopen this PR.

**Comment by RaymondMouthaan** [comment]
Hi @ThomDietrich & @baurmatt,

After more than a year of waiting for approval, I closed it. 

Probably in its current state its no longer up2date. Myself, I no longer use the 'miflora-mqtt-daemon` approach and replaced with an esp32 which acts like a bridge between miflora and mqtt [miflora-esp32](https://github.com/RaymondMouthaan/miflora-esp32). 

If you guys like to adopt the PR, feel free to do so and I case of questions I am available to help.

**Pull request closed without merging**
